install.packages("ggplot2")
install.packages("FactoMineR")
install.packages("factoextra")
install.packages("readxl")
install.packages("dplyr")
library ("ggplot2")
library ("FactoMineR")
library ("factoextra")
library(readxl)
library("dplyr")
CI <- read_excel("C:/Users/HY/Desktop/CI_PCA.xlsx")
View(CI)
res.pca <- PCA(CI[, -234], graph = FALSE)
CI$Species <- factor(CI$Species, levels = c('CI', 'Control'))
fviz_pca_ind(res.pca, label = "none", habillage = CI$Species, palette = c("#FC4E07", "#00AFBB"))

